---
# tasks file for nginx
- name: Add offical nginx repositories
  yum_repository:
    name: nginx
    description: nginx offical repositories
    file: nginx
    baseurl: http://nginx.org/packages/centos/7/x86_64/
    gpgcheck: no
    enabled: yes

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Copy nginx default config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: Makesure service enabled and started
  systemd:
    name: nginx
    state: started
    enabled: yes
