- name: stopping rabbitmq app
  command: rabbitmqctl stop_app
  when: ansible_ssh_host not in groups.master

- name: joining rabbitmq cluster
  command: rabbitmqctl join_cluster 'rabbit@master'
  when: ansible_ssh_host not in groups.master

- name: starting rabbitmq app
  command: rabbitmqctl start_app
  when: ansible_ssh_host not in groups.master

- name: marking as clustered
  file:
    path: /etc/rabbitmq/clustered
    state: touch

- name: create user and vhost
  shell: |
     rabbitmqctl add_user admin admin
     rabbitmqctl set_user_tags admin administrator
     rabbitmqctl set_permissions -p / admin  ".*" ".*" ".*"
     rabbitmqctl add_vhost /eventbustest
     rabbitmqctl add_user eventuser @event2016
     rabbitmqctl set_permissions -p /eventbustest eventuser ".*" ".*" ".*"
  args:
    warn: no
  when: inventory_hostname in groups['master']

