---
- name: Set rc.local can be execution
  file:
    path: /etc/rc.d/rc.local
    owner: root
    group: root
    mode: 0755

- name: Set timezone to Asia/Shanghai
  lineinfile:
    path: /etc/profile
    regexp: "^export TZ="
    line: 'export TZ="Asia/Shanghai"'

- name: Set the datetime
  shell: timedatectl set-local-rtc 1

- name: Disable SELinux
  selinux:
    state: disabled
#TODO Need to confirm the firewalld was closed
# - name: Dsiable Firewalld
#   systemd:
#     state: stopped
#     name: firewalld
#     enabled: no
#     masked: yes
#   tags:
#     - disable_firewalld

- name: Add or modify nofile soft limit
  pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: nofile
    value: "655360"

- name: Set ipv4 forward
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes

- name: Setup for Redhat Series
  import_tasks:
    - redhat.yml
  when: ansible_distribution == "RedHat"

- name: Setup for Debian Series
  import_tasks:
    - ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Add user rancher to docker group
  user:
    name: rancher
    uid: 1040
    groups: [docker]
    append: yes
  become: yes

- name: Setting the passwd for rancher
  shell: echo rancher|passwd rancher --stdin
#############################################
# Example for deploying the offline enviroments
# - name: add unzip rpm
#   copy:
#     src: "unzip-6.0-20.el7.x86_64.rpm"
#     dest: /tmp/unzip-6.0-20.el7.x86_64.rpm

# - name: yum install unzip
#   yum:
#     name:
#     - /tmp/unzip-6.0-20.el7.x86_64.rpm
#     state: present
#############################################
